<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <PackageId>BrandonPowers.PortalAPI</PackageId>
    <Version>1.2.1</Version>
    <Authors>Brandon Powers</Authors>
    <Description>Client library for the application API</Description>
    <RepositoryUrl>https://github.com/brandonRpowers/Huron-Portal-WebServices-API</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
  </ItemGroup>
</Project>
