<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>BrandonPowers.PortalAPI</PackageId>
    <Version>1.0.0</Version>
    <Authors>Brandon Powers</Authors>
    <Description>Client library for the application API</Description>
    <RepositoryUrl>https://github.com/brandonRpowers/Huron-Portal-WebServices-API</RepositoryUrl>
  </PropertyGroup>
</Project>
